[package]
name = "polling"
version = "2.0.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "Portable interface to epoll, kqueue, event ports, and wepoll"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stjepang/polling"
homepage = "https://github.com/stjepang/polling"
documentation = "https://docs.rs/polling"
keywords = ["mio", "epoll", "kqueue", "iocp", "wepoll"]
categories = ["asynchronous", "network-programming", "os"]
readme = "README.md"

[features]
default = ["std"]
std = []

[dependencies]
cfg-if = "0.1.10"
log = "0.4.11"

[target."cfg(unix)".dependencies]
libc = "0.2.77"

[target.'cfg(windows)'.dependencies]
wepoll-sys = "3.0.0"
winapi = { version = "0.3.9", features = ["ioapiset", "winsock2"] }

[dev-dependencies]
easy-parallel = "3.1.0"
